### ISSUE TITLE
Use props render in MultilList, SelectedFilter cannot clear item

### ISSUE THREAD

**Issue by longnk1301-vmodev** [appbaseio/reactivesearch#1490] opened 2020-06-09 03:32 UTC
**
I have issue when use render for MultiList, so then I cannot clear item selected on SelectedFilter, please give me any solution, thanks!!
**

**Comment by jyash97** [comment] 2020-06-09 06:24
Hey @longnk1301-vmodev can you please follow the issue template and create a sample CodeSandbox Link which shows the issue?

**Comment by acosta-edgar** [comment] 2020-07-22 03:43
Hey @longnk1301-vmodev , could your report be a duplicate of #1512 ?

**Comment by bietkul** [comment] 2020-08-04 04:42
@longnk1301-vmodev Track it here #1512

**Closed as completed by bietkul** 2020-08-04 04:42 UTC
Labels: bug, Needs Example, Needs More Info
