### ISSUE TITLE
Crash if SingleDropdownList's parent changes

### ISSUE THREAD

**Issue by axeff** [appbaseio/reactivesearch#667] opened 2018-12-06 12:44 UTC
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
If the parent of a SingleDropdownList changes, the whole app crashes.

**Minimal reproduction of the problem with instructions:**
See [codesandbox example](https://codesandbox.io/s/vmqkypz22y) for reproduction.
When you click the button, the parent of the List component changes to a div and vice versa.

The thing is I try to render two different filter menus depending on screen resolution.
For desktop it will be displayed straight, as tablet it will be rendered into some slide out menu.
And everytime I change tablet portrait to landscape (same as tablet to dektop) the whole app crashes.

**Reactivesearch version:** x.y.z
2.x

**Browser:**
all

**Anything else:**
`TypeError
Cannot read property 'original_series.raw' of undefined`

**Comment by metagrover** [comment] 2018-12-10 07:35
Hi @axeff, until we roll out a fix for this - you can change the `SingleDropdownList` component's `componentId` on wrapper change to get around this issue.

**Comment by axeff** [comment] 2018-12-10 15:44
@metagrover I realised that but that's no option since we have strong focus on SSR. And I would expect the google bot to not like that same content on different params of the url based on the device type.

**Comment by metagrover** [comment] 2018-12-10 16:00
Alright, I understand. I will try to get the fix out soon (Expect 2-3 days).

**Comment by jyash97** [comment] 2018-12-27 10:14
Hey @axeff
Here is the detailed description of this issue.
###  Why this is Happening?
We are running into this error because `SingleDropdownList`'s `componentWillUnmount` is getting triggered lazily and hence the clean up happens (asynchronously) after the re-mounted component's `componentWillMount` is executed which is expected behavior as per react.

Since we have same `componentId` both of the components are removed from the store and everything breaks as we don't have the track of the component now.

### When will this happen
Whenever we `remount` the component, either by changing the `key` of the component or by manually unmounting and mounting as done [here](https://codesandbox.io/s/vmqkypz22y).

### Components Affected
> All Components

### Solution
- **Library Level**
Using `setTimeout` with zero delay on `componentWillMount` function body but this will create other side effects which may cause other errors. So this is not feasible.

- **App Level** 
In order for remount to work properly, we should remount the component on zero-delay (https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Zero_delays) using setTimeout.
Check the example implementation [here](https://codesandbox.io/s/xrq4320mx4)

**Closed** 2019-03-01 14:05 UTC
Labels: bug
