### ISSUE TITLE
Issue with pagination when redirects with query params

### ISSUE THREAD

**Issue by riddhiparekh** [appbaseio/reactivesearch#1629] opened 2021-03-18 12:40 UTC
**Affected Projects**
React
**Library Version:**^3.12.4

**Describe the bug**
With `URLParams=true` on `ReactiveList`, 
When on Any page other than 1st, after refreshing browser, user gets on that page, but once user change the page and visit same page again, by click on pagination, it redirects user to 1st page rather than that page.

**To Reproduce**
[Source](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/next/packages/web/examples/ReactiveList?from-embed)
In above sandbox, go to page 2, refresh `preview window`, it will retain page 2,
now click on page 3, and again click back to page 2, it will redirect to page 1.

**Expected behavior**
It should redirect to page which is selected and not 1st page.

**Screenshots**
[Here](https://www.screencast.com/t/8bIvk7i7B) I have demonstrated exact scenario performed on [sandbox here ](https://oipfn.sse.codesandbox.io/?SearchResult=1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 89.0

**Comment by bietkul** [comment] 2021-06-25 18:34
@riddhiparekh It seems like a duplicate of #1701 that has been fixed in the latest version.

**Closed as completed by bietkul** 2021-06-25 18:34 UTC
Labels: bug
