### ISSUE TITLE
Extra request on page load

### ISSUE THREAD

**Issue by willopez** [appbaseio/reactivesearch#834] opened 2019-02-15 23:33 UTC
**Issue Type:** Bug

**Platform:** Web

**Description:**

I followed the example here: https://github.com/appbaseio/reactivesearch/tree/v2.16.1/packages/web/examples/ssr-with-react-dom to implement SSR in my app. The app correctly renders on the server and it's hydrated on the client. However, once the page has loaded, an extra `match_all`(the default query) request is fired, which is unnecessary since the data is already present in the ReactiveSearch store. Wondering, why this is happening? 

**Reactivesearch version:** 2.16.1

**Browser:** [Chrome 72 ]

**Comment by metagrover** [comment] 2019-02-19 10:35
Thanks for filing this. I will look into this!

**Comment by willopez** [comment] 2019-02-20 00:35
More details: The issue is related to setting the initial search value on the server. No extra request will be fired if the default `match_all` query is fired. However, when an initial search value is provided, here: https://github.com/appbaseio/reactivesearch/blob/v2.16.1/packages/web/examples/ssr-with-react-dom/server/server.js#L95 an extra request is fired when the page loads.

**Comment by metagrover** [comment] 2019-02-20 06:32
Is this happening on v3.x?

**Comment by willopez** [comment] 2019-02-20 17:07
I experienced the same behavior on v2.x, and I am now an v3.x and I see the same behavior.

**Comment by metagrover** [comment] 2019-02-28 09:40
This has been possibly fixed (unable to replicate now) with 1b4faeffeb566a983c661e9c4d938a896ed18232

Please check once the new release `v3.0.0-beta.8` is out (~later today).

Feel free to reopen if you still face the issue.

**Comment by willopez** [comment] 2019-03-04 17:05
I still see this issue in `beta.8` reproduced in this repo: https://github.com/willopez/ssr-with-react-dom. I believe this issue should be reopened.

**Comment by metagrover** [comment] 2019-03-04 17:06
Sure, will take a look. Thanks!

**Comment by willopez** [comment] 2019-03-06 22:12
thanks @metagrover, and any update on this issue?

**Comment by metagrover** [comment] 2019-03-07 06:51
Hey @willopez I will try to squeeze in some time early next week to look into this. Thanks for patience. We really want to get this right from our end.

**Comment by willopez** [comment] 2019-03-22 21:29
Hi @metagrover any questions or updates on this issue?

**Comment by metagrover** [comment] 2019-03-25 11:04
@bietkul Please check on this.

**Comment by lakhansamani** [comment] 2019-04-04 16:08
@willopez I have investigated on the above issue
So following are the reason for extra network requests on the browser

1. `SearchResult` was triggering extra request because of improper `react` prop configuration, You can check the correct configuration for sample application you shared over here (react prop should have been same on client and server otherwise it could change the query)
https://github.com/willopez/ssr-with-react-dom/pull/1/files

2. `SearchSensor` was triggering extra request because of autosuggest prop true on the client side, it is the expected behaviour as input value is changed based on query param over there. https://github.com/willopez/ssr-with-react-dom/pull/1/files#diff-895656aeaccff5d7c0f56a113ede9662R24

Closing the Issue for now.

**Closed as completed by lakhansamani** 2019-04-04 16:08 UTC

**Comment by redlinecodes** [comment] 2019-04-27 14:41
@lakhansamani - Is this issue fixed in v3x?
