### ISSUE TITLE
Adding Header with API Key doesn't work due to URL encoding

### ISSUE THREAD

**Issue by rccoe** [appbaseio/reactivesearch#1235] opened 2019-11-14 17:33 UTC
**Affected Projects**
React

**Library Version:** x.y.z
3.0.3

**Describe the bug**
Using a header to pass an API key doesn't work, as the space gets URL encoded. 

**To Reproduce**

```
<ReactiveBase
            app="hpro"
            url={config.URL}
            headers={{ Authorization: `ApiKey ${config.API_KEY}` }}
        >
```

Header gets sent as

`authorization: ApiKey%20[[API_KEY]]`

**Expected behavior**
That requests will work given an API key header

**Screenshots**

**Desktop (please complete the following information):**
Browsers: All

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bietkul** [comment] 2019-11-14 17:35
It's a duplicate of #958.

**Closed as completed by bietkul** 2019-11-14 17:35 UTC
Labels: bug
