### ISSUE TITLE
Dynamic range slider does not render

### ISSUE THREAD

**Issue by royduin** [appbaseio/reactivesearch#1556] opened 2020-10-28 08:45 UTC
**Affected Projects**
Vue.JS

**Library Version:**
1.7.7

**Describe the bug**
Dynamic range slider does not render

**To Reproduce**
https://codesandbox.io/s/nice-matsumoto-ubg5m?file=/src/App.vue

**Comment by hansendx** [comment] 2020-11-18 09:40
This is a problem since version 1.4.1 #1501

**Comment by indykoning** [comment] 2020-11-20 14:32
It seems to have broken during the update to 1.4.1 
https://github.com/appbaseio/reactivesearch/compare/v1.4.0-vue...v1.4.1-vue

The slider is not showing because the range is null, it seems like range does not get filled dynamically.
https://github.com/appbaseio/reactivesearch/blob/next/packages/vue/src/components/range/DynamicRangeSlider.jsx#L275
Moreover setting this to a range using vue devtools shows the slider, however after filtering or updating it in some other way once again forces it to be null.

**Comment by bietkul** [comment] 2020-12-22 20:53
Duplicate of #1501

**Closed as completed by bietkul** 2020-12-22 20:53 UTC
Labels: bug
