### ISSUE TITLE
parseSuggestion introduces duplicate results with DataSearch and highlighting does not work

### ISSUE THREAD

**Issue by dojutsu-user** [appbaseio/reactivesearch#1002] opened 2019-05-28 16:11 UTC
**Issue Type:**
Bug
**Platform:**
Reactivesearch web

**Description:**
I am using reactivesearch to build a search for books. Here is the Datasearch component:
```js
<DataSearch
  className="main_datasearch"
  componentId="SearchSensor"
  dataField={["title", "author", "publisher", "year", "isbn"]}
  fieldWeights={[20, 18, 16, 14, 14]}
  fuzziness={2}
  highlight={true}
  highlightField={["title", "author", "publisher", "year", "isbn"]}
  customHighlight={props => {
    return {
      highlight: {
        pre_tags: ["<mark>"],
        post_tags: ["</mark>"],
        fields: {
          title: {},
          author: {},
          publisher: {},
          year: {},
          isbn: {}
        },
        number_of_fragments: 0
      }
    };
  }}
  parseSuggestion={suggestion => {
    return {
      label: (
        <div className="book__result__hit">
          <h2>{suggestion.source.title}</h2>
          <p>
            <i>by</i> {suggestion.source.author}
          </p>
          <small>ISBN: {suggestion.source.isbn}</small>
          <small>
            Publisher: {suggestion.source.publisher} (
            {suggestion.source.year})
          </small>
        </div>
      ),
      value: suggestion.source.title,
      source: suggestion.source
    };
  }}
/>
```

This is introducing duplicates in the suggestions. And also the highlighting settings seems to have no effect on suggestions.

**Screenshots:**
![ezgif-1-9ae5c1afbe8a](https://user-images.githubusercontent.com/29149191/58493335-54d48b80-8190-11e9-8e1f-c2425dd13b3b.gif)

**Minimal reproduction of the problem with instructions:**
Elasticsearch mappings is like this -
```json
{
  "mapping": {
    "doc": {
      "properties": {
        "author": {
          "type": "text"
        },
        "id": {
          "type": "long"
        },
        "image_url": {
          "type": "keyword"
        },
        "isbn": {
          "type": "keyword"
        },
        "publisher": {
          "type": "text"
        },
        "title": {
          "type": "text"
        },
        "year": {
          "type": "keyword"
        }
      }
    }
  }
}
```

And Datasearch Component with attributes is same as mentioned above.
**Reactivesearch version:** x.y.z
Reactivesearch version as mentioned in package.json: `3.0.0-rc.12`

**Browser:** all
**Operating System:** Ubuntu 18.04.2 LTS

**Anything else:**
N/A

**Comment by bietkul** [comment] 2019-06-03 11:19
Can you please share some reproducible demo?

**Comment by joergac** [comment] 2019-06-08 08:17
I can confirm this is an issue for me too.

**Comment by mauxtin** [comment] 2019-06-27 19:17
I am actually having the same issue on the Vue library. Can only reproduce with some searches only and the actual request's response returns only one result (but I am seeing it twice when rendering). Possibly an issue with the reactivecore.

**Comment by dojutsu-user** [comment] 2019-06-28 03:18
@bietkul 
It would be great help if you can look into this.
I think the index mapping, screenshot and DataSeach component is sufficient to reproduce this error.
And if you need any more info, please do tell.

**Comment by bietkul** [comment] 2019-06-28 09:31
@dojutsu-user I tried to replicate the issue but no luck, it seems to be working fine [here](https://opensource.appbase.io/playground/?path=/story/search-components-datasearch--with-parsesuggestion) too.
It would be really helpful if you can create a code sandbox or codepen example.

**Comment by dojutsu-user** [comment] 2019-06-28 16:38
@bietkul 
You can produce the error with this -- https://codesandbox.io/s/frosty-wildflower-2ukr4?fontsize=14
Just type `a` and you will see the results.

**Comment by bietkul** [comment] 2019-06-28 16:42
@dojutsu-user Thanks, I can see the issue.
It'll be fixed soon.

**Comment by dojutsu-user** [comment] 2019-06-28 16:46
@bietkul Thanks for working on this. :tada:

**Comment by bietkul** [comment] 2019-06-28 18:28
After digging more on it, I found that we extract the keywords (suggestions) from the returned hits based on the defined fields(`dataFields`) i.e if a query returns a total of 10 results than the actual suggestions can be greater than 10.
In your example, the generated suggestions are `50` from the `20` hits.
The data fields defined by you are:
```
['title', 'author', 'publisher', 'year', 'isbn']
```
So, the suggestions will have the value of all these fields i.e we can only guarantee the uniqueness of `label`  field, `source` can be same for some suggestions.

Solution: 
1. Use `label` key for the title or define `dataFields` in a way that it won't replicate the `source`.
2. If the first method doesn't work then you can use custom `render` function to render the suggestions.
https://opensource.appbase.io/reactive-manual/search-components/datasearch.html#props

**Comment by bietkul** [comment] 2019-07-01 08:46
Since it doesn't seem to be a library issue, so closing it for now.
Lmk if it doesn't work.

**Closed as completed by bietkul** 2019-07-01 08:46 UTC
Labels: Needs Investigation

**Comment by mauxtin** [comment] 2019-07-15 18:26
Hey @bietkul, is there any way to manipulate the data before rendering in this case (in Vue)?

I tried to add a `transformResponse` on the `ReactiveBase` but since the response only has one result it doesn't make sense to do so.

Ideally I would like to avoid overriding the whole `render` method for this.

The duplication happens inside the library so I think this **is** a library issue.. Is there any other way to solve this?
