### ISSUE TITLE
[Vue] Object doesn't support property or method 'endsWith'

### ISSUE THREAD

**Issue by mauxtin** [appbaseio/reactivesearch#815] opened 2019-02-04 12:56 UTC
I am currently getting a lot of this sentry exceptions. Didn't have the chance to check it further but here is the stack trace. The page loads fine as far as I can see though.

```
TypeError: Object doesn't support property or method 'endsWith'
  at Anonymous function(./node_modules/@appbaseio/reactivecore/lib/actions/query.js:1:8384)
  at Anonymous function(./node_modules/redux-thunk/es/index.js:7:1)
  at dispatch(./node_modules/redux/es/redux.js:611:1)
  at Anonymous function(./node_modules/@appbaseio/reactivecore/lib/actions/query.js:1:8689)
  at Anonymous function(./node_modules/redux-thunk/es/index.js:7:1)
  at this(./node_modules/redux/es/redux.js:462:1)
  at this(./node_modules/@appbaseio/reactivesearch-vue/dist/@appbaseio/reactivesearch-vue.es.js:6798:1)
  at handlers(./node_modules/@appbaseio/reactivesearch-vue/dist/@appbaseio/reactivesearch-vue.es.js:6896:1)
  at callHook(./node_modules/vue/dist/vue.runtime.esm.js:3038:1)
  at Anonymous function(./node_modules/vue/dist/vue.runtime.esm.js:2921:1)
  at vnode(./node_modules/vue/dist/vue.runtime.esm.js:8070:1)
  at ln.init(./node_modules/vue/dist/vue.runtime.esm.js:4235:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6087:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6121:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:6202:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:2781:1)
  at value(./node_modules/vue/dist/vue.runtime.esm.js:2899:1)
  at this(./node_modules/vue/dist/vue.runtime.esm.js:3269:1)
  at Fe(./node_modules/vue/dist/vue.runtime.esm.js:3256:1)
  at Anonymous function(./node_modules/vue/dist/vue.runtime.esm.js:2921:1)
  at vnode(./node_modules/vue/dist/vue.runtime.esm.js:8070:1)
  at ln.init(./node_modules/vue/dist/vue.runtime.esm.js:4235:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6087:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6121:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6121:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6121:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:6202:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:2781:1)
  at value(./node_modules/vue/dist/vue.runtime.esm.js:2899:1)
  at this(./node_modules/vue/dist/vue.runtime.esm.js:3269:1)
  at Fe(./node_modules/vue/dist/vue.runtime.esm.js:3256:1)
  at Anonymous function(./node_modules/vue/dist/vue.runtime.esm.js:2921:1)
  at vnode(./node_modules/vue/dist/vue.runtime.esm.js:8070:1)
  at tag(./node_modules/vue/dist/vue.runtime.esm.js:4235:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6071:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6121:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:6202:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:2781:1)
  at value(./node_modules/vue/dist/vue.runtime.esm.js:2899:1)
  at this(./node_modules/vue/dist/vue.runtime.esm.js:3269:1)
  at Fe(./node_modules/vue/dist/vue.runtime.esm.js:3256:1)
  at Anonymous function(./node_modules/vue/dist/vue.runtime.esm.js:2921:1)
  at vnode(./node_modules/vue/dist/vue.runtime.esm.js:8070:1)
  at tag(./node_modules/vue/dist/vue.runtime.esm.js:4235:1)
  at hydrate(./node_modules/vue/dist/vue.runtime.esm.js:6071:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:6202:1)
  at vm(./node_modules/vue/dist/vue.runtime.esm.js:2781:1)
  at value(./node_modules/vue/dist/vue.runtime.esm.js:2899:1)
  at this(./node_modules/vue/dist/vue.runtime.esm.js:3269:1)
  at Fe(./node_modules/vue/dist/vue.runtime.esm.js:3256:1)

```

**Comment by bietkul** [comment] 2019-02-04 15:39
Hey @mauxtin,
Can you please share some more details about it?
like what are the components being used in your code
I think this line is causing the issue https://github.com/appbaseio/reactivecore/blob/master/src/actions/query.js#L421 which can be simply fixed by using a check, but still, we want to know the root cause from vue library.

**Comment by mauxtin** [comment] 2019-02-05 20:19
Hi @bietkul, 

This seems to occur in multiple components (saw it in MultiList and ReactiveList) but I noticed that it only happens in IE11 so I am thinking that my `babel-preset-app` might me misconfigured. 

I will continue to investigate since I receive too many error notifications lately about this particular error. Would it make sense for `babel-preset-app` to be causing something like this?

**Comment by bietkul** [comment] 2019-02-05 22:43
@metagrover It seems like a known issue https://stackoverflow.com/questions/29434868/script438-object-doesnt-support-property-or-method-endswith-in-ie10
Any idea, what can be the best solution here?

**Comment by metagrover** [comment] 2019-02-06 08:51
We can add it as a polyfill in vue setup. Similar to https://github.com/appbaseio/reactivesearch/commit/96bcc162b955fae6a75fa2554ede89576dc9ec61.

**Comment by bietkul** [comment] 2019-02-06 09:55
cool, so basically we need to handle `endsWith` too in this file.
https://github.com/appbaseio/reactivesearch/blob/96bcc162b955fae6a75fa2554ede89576dc9ec61/packages/web/src/polyfills.js
Can we move this file in reactivecore?

**Comment by metagrover** [comment] 2019-02-06 10:20
okay, let's do that.

**Closed as completed** 2019-02-06 12:47 UTC
