### ISSUE TITLE
Improvements to bundle size on reactivesearch-vue

### ISSUE THREAD

**Issue by jpsc** [appbaseio/reactivesearch#1630] opened 2021-03-18 12:45 UTC
**Affected Projects**
Vue.js

**Is your feature request related to a problem? Please describe.**
Reactivesearch provides building blocks (ReactiveBase) to create your own custom components. This allows anyone to sidestep existing components that are not directly relevant for the page they are building. This is great but how it is currently implemented, regardless if you use or not, all components are going to be included on your bundle. 

The documentation [refers that you can](https://docs.appbase.io/docs/reactivesearch/vue/overview/QuickStart/#only-register-the-components-you-need-recommended) use specific components but it will still add all to the bundle. 

**Describe the solution you'd like**
It would be nice if we could import only the components that we want to use and not the whole set of components. eg: Importing the `ReactiveBase` should not bring `vue-slider-component`.

**Describe alternatives you've considered**
None

**Additional context**
I am running all this with Nuxt and SSR.
You can check [this repo with a reproduction](https://github.com/jpsc/appbase-bundle-repro) and run ``` npm run analyze```.

**Comment by larsdouweschuitema** [comment] 2021-04-20 11:45
@bietkul @lakhansamani Is this something you will look into?

**Comment by bietkul** [comment] 2021-04-20 12:09
@jpsc Thanks for the example we can replicate the issue easily. 
Despite exporting the ES6 modules from the build file, the tree shaking is not working. We have to debug the root cause. You can expect it to be fixed by the end of this week. We'll keep you updated.

**Comment by bietkul** [comment] 2021-04-21 19:53
@jpsc @larsdouweschuitema A new version(`v1.13.1`) is out with the fix.

**Closed as completed by bietkul** 2021-04-21 19:53 UTC
Labels: enhancement
